name: Fetch and Save User Agents

on:
  schedule:
    - cron: '0 23 * * *' # Run daily at 23:00 hours
  workflow_dispatch:

jobs:
  fetch-and-save-user-agents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Fetch User Agents and Save JSON
      env:
        API_KEY: ${{ secrets.WHATISMYBROWSER_KEY }}
      run: |
        mkdir -p user-agents
        for software in chrome edge safari firefox firefox-esr
        do
          curl -H "X-API-KEY: $API_KEY" "https://api.whatismybrowser.com/api/v2/user_agent_database_search?order_by=times_seen%20desc&hardware_type=computer&limit=500&offset=500&software_name=$software" \
          -o "user-agents/${software}.json"
        done

    - name: Extract User Agents and Save to File
      run: |
        mkdir -p user-agents
        > user-agents/all.txt
        for file in user-agents/*.json
        do
          jq -r '.search_results.user_agents[].user_agent' "$file" >> user-agents/all.txt
        done

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add user-agents/
        git commit -m 'Update user agents data' || echo "No changes to commit"
        git push
        for software in software_names:
            params = {
                "order_by": "times_seen desc",
                "hardware_type": "computer",
                "limit": 500,
                "offset": 500,
                "software_name": software
            }
            headers = {
                "X-API-KEY": API_KEY
            }
            response = requests.get(base_url, headers=headers, params=params)
            if response.status_code == 200:
                with open(f"user-agents/{software}.json", "w") as file:
                    json.dump(response.json(), file)

    - name: Extract User Agents
      run: |
        import json
        import glob

        user_agents = []
        for filename in glob.glob('user-agents/*.json'):
            with open(filename, 'r') as file:
                data = json.load(file)
                user_agents.extend([ua['user_agent'] for ua in data['search_results']['user_agents']])

        with open('user-agents/all.txt', 'w') as file:
            file.write('\n'.join(user_agents))

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add user-agents/*.json user-agents/all.txt
        git commit -m 'Update user agents data'
        git push
